name: Cloud Assyst Middleware CICD buid

on:
  push:
    #paths: [ "src/middleware/**" ]
    branches: [ "main" ]

jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm run test
        npm run test:cov
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      env:
        CODECOV_TOKEN: bb2f5e25-c2b5-4120-a855-88000354ee04
        slug: deepaktekk/test